### ISSUE TITLE
Error when using flux1-dev-bnb-nf4.

### ISSUE THREAD

**Issue by VeteranXT** [lllyasviel/stable-diffusion-webui-forge#1066]
```Error named symbol not found at line 90 in file D:\a\bitsandbytes\bitsandbytes\csrc\ops.cu```
I've checked file, it's ghost file!
flux1-dev-fp8 works fine.

**Comment by MikeyTsunami** [comment]
Same boat. Curious if you're running this on or Nvidia and AMD. With a 6800xt I have to use the Zluda variants on windows and tend to assume any errors stem from the GPU, so wondering what you're using. Tried Forge and Comfy with same the end result despite the different configurations required within both UIs.

**Comment by meteor-fsk** [comment]
I use an AMD graphics card. I'm using zluda on Windows to run comfyui. The same error is displayed

**Comment by Kagamine-Rinrin** [comment]
> I use an AMD graphics card. I'm using zluda on Windows to run comfyui. The same error is displayed
Me too

**Comment by VeteranXT** [comment]
Using RX 6600 XT AMD GPU.

**Comment by jonatj** [comment]
I'm getting the same error on Win11 and AMD 6800XT with ZLUDA. So must be some CUDA code that ZLUDA can't handle or that conflicts with our AMD GPUs.

**Comment by Donased** [comment]
Same error, with a 7800XT

**Comment by cassis07** [comment]
I get the same error message: Error named Symbol not found at line 90 in file D:\a\bitsandbytes\bitsandbytes\csrc\ops.cu

This directory doesn't even exist because I only work on C:.

I use a Radeon RX 6700 XT graphics card and ComfyUI with Zluda. It actually runs smoothly with the other Flux models. It's just pretty slow. When I want to integrate the FLUX NF4 model, i always get the error message from above in this workflow. With another workflow I then get this error message: "Error occurred when executing UNETLoader:" I don't know what to do anymore...

**Comment by magictext** [comment]
@VeteranXT I see that you closed this issue. Did you find a solution?

**Comment by VeteranXT** [comment]
Here is why I did close it. 
![358868358-4a776ff3-e2e2-4942-b9f0-912360341c60](https://github.com/user-attachments/assets/a1436fa0-acf5-4c54-bc68-73b90986dfd9)
