### ISSUE TITLE
You are breaking webui's interface for non-backend extensions

### ISSUE THREAD

**Issue by light-and-ray** [lllyasviel/stable-diffusion-webui-forge#109]
Hello, I've seen then you've added processed.extra_images. Processed - is one of the key part of interface on which extensions rely. Other extension, which are far from backend, rely on that they can find all result images inside processed.images. To resolve which images are generated in sd, we can check processed.all_seeds

You are breaking compatibility with non-backend webui's extensions. Maybe you want to develop completley new fork like sd-next, but I thought the purpose of forge is different (

**Comment by lllyasviel** [comment]
when i add images to processed.images, some versions of ultimate sd upscale, reactor, adetailer failed because some do not know the trick processed.all_seeds, and they sometimes will run face detection/restoration on the canny edge maps 

adding processed.extra_images fixed these and now they work well

besides are you willing to join the collaboration of this repo for further discussions?

**Comment by lllyasviel** [comment]
do you have same direct examples what processed.extra_images is breaking now?

**Comment by lllyasviel** [comment]
thanks for the suggestions.

let me know if we have direct examples about which extension will be broken with this extra filed and i will take a look
