### ISSUE TITLE
Why are most of the images generated by the flux model blurry?

### ISSUE THREAD

**Issue by xldistance** [lllyasviel/stable-diffusion-webui-forge#1157]
I've tried all kinds of parameters but the result is still the same blurred image
![QQ截图20240816012521](https://github.com/user-attachments/assets/5ae1acef-057b-4a88-bd57-089b8f2ae8a5)

**Comment by 111111111111111111111111111111111111110** [comment]
try euler, beta

**Comment by xldistance** [comment]
> try euler, beta
> 
> distilled cfg scale -> 3.5

Thank you. Sampling method set to Euler.
Euler
Schedule type is set to Beta, and the image can be generated normally.

**Comment by HMRMike** [comment]
Also interesting combinations: Heun-SGM Uniform, Euler-DDIM,

**Comment by adde88** [comment]
Nice, this thread helped me alot with blurry issues on some certain FLUX models. But damn, gotta love FLUX! :D

**Comment by Symbiomatrix** [comment]
Leaving a note here just in case (for anyone else like myself who tends to skim guides): Blurriness in flux is also caused by having cfg > 1. It's supposed to be set to 1 and use distilled cfg. Negative prompt is disabled.

**Comment by sup2069** [comment]
> Leaving a note here just in case (for anyone who like myself tends to skim guides): Blurriness in flux is also caused by having cfg > 1. It's supposed to be set to 1 and use distilled cfg. Negative prompt is disabled. Apologies for the hijack.

This helped thanks! Had it on from another flux checkpoint that used both! 🤝

**Comment by iamdevilal** [comment]
I changed from steps 20 to 26, and it solved. every other settings including euler, simple was ok

**Comment by teller657** [comment]
> Leaving a note here just in case (for anyone who like myself tends to skim guides): Blurriness in flux is also caused by having cfg > 1. It's supposed to be set to 1 and use distilled cfg. Negative prompt is disabled. Apologies for the hijack.

@Symbiomatrix may have saved my life with this comment. That is how I got here and I would have never figured out what I did by sliding the cfg greater than 1.

**Comment by Archviz360** [comment]
i have tried with all tips buyt still getting blurry images.

**Comment by Archviz360** [comment]
im using forge ui via pinokio nad still getting blur even if i have done all tips. i cant find even solid solution for it.

**Comment by Fembro-Brite** [comment]
> i have tried with all tips buyt still getting blurry images.

Look here is the truth about Flux, as we dated for a while on Weights.com. Flux has Bipolar 2, and he is always in a state of...well Flux. We used to fight a lot and deep down he means well but I told him to either see a specialist or I'm just going to go make sexy pictures with a more stable diffusion model. After rendering me as a pile of disfigured parts in a pool of my own blood as though he threw me out of an air plane onto the concrete, he realized his conditioning values were all over the place and was losing net control so we went together and they put him on this Anti-Blur-Lora medication and now his moods have stabilized. Since all these models are a copy of the same one you will have to put him on this anti-blur medication. It turns out this was inherited from his developers through transference so unfortunately as long as who ever is working at Black Forest Labs is training they are all going to be temperamental. 

https://civitai.com/models/675581/anti-blur-flux-lora
