### ISSUE TITLE
"Cancel generate forever" is blocked

### ISSUE THREAD

**Issue by jil49300** [lllyasviel/stable-diffusion-webui-forge#1190]
Since new version, "Cancel generate forver" does not work any longer.
You have to close the python windows and lauch Forge again to work further ...

**Comment by itasky** [comment]
you can reload the UI trhough the browswer (F5) and then it will stop.

**Comment by SuperMaoUwU** [comment]
> Since new version, "Cancel generate forver" does not work any longer. You have to close the python windows and lauch Forge again to work further ...

this was the cse before too haha

**Comment by Fretag** [comment]
I noticed this back when the big update began and have stopped trying to use it. It did it again today. I end up having to shut it all down and restart again.

**Comment by MBurneracc** [comment]
One of the many fuck ups to simple core features they don't really seem to care about.  But hey, at least now it supports flux... kind of...

**Comment by SuperMaoUwU** [comment]
> One of the many fuck ups to simple core features they don't really seem to care about. But hey, at least now it supports flux... kind of...

You do realize that this is a single dude maintaining it and not a multi billion dollar company right?

**Comment by MBurneracc** [comment]
> You do realize that this is a single dude maintaining it and not a multi billion dollar company right?

I realize that a week of construction just to support a new model doesn't amount to much if it breaks a ton of other shit in the process.  Can't use generate forever any more without breaking the ui and needing to refresh the browser, can't do XYZ plots with checkpoints/vae, can't use several longstanding extensions that are just dead now and all apparently because they just arbitrarily deleted stuff they didn't think was important and then moved on to something new.  All to kind of support Flux and offer worse performance overall for everything else.

**Comment by MBurneracc** [comment]
Because I use Stability Matrix to manage my install, and in their infinite wisdom the only installation options they let you choose from are the ten most recent commits meaning the oldest version I can roll  back to is like yesterday.

**Comment by TheStagnation** [comment]
> I realize that a week of construction just to support a new model doesn't amount to much if it breaks a ton of other shit in the process. Can't use generate forever any more without breaking the ui and needing to refresh the browser, can't do XYZ plots with checkpoints/vae, can't use several longstanding extensions that are just dead now and all apparently because they just arbitrarily deleted stuff they didn't think was important and then moved on to something new. All to kind of support Flux and offer worse performance overall for everything else.

ai was the worst thing to happen to github, because people like you think it's to voice complaints instead of report bugs and suggest fixes. your comments are made for twitter and 4chan, not here. clear comms and let the developer cook.

**Comment by MBurneracc** [comment]
> ai was the worst thing to happen to github, because people like you think it's to voice complaints instead of report bugs and suggest fixes. your comments are made for twitter and 4chan, not here. clear comms and let the developer cook.

I've been reporting bugs for the past week, lots of people have because there are so god damn many of them.  I've watched people report bugs, get tired of waiting, figure out the solutions themselves and still get ignored.  If this is a developer "cooking" then they deserve a visit from the health inspector and a big F in the window.  This was a perfectly fine UI until they decided to rewrite the thing themselves and started off by just deleting vast swathes of code they didn't think was important but was holding things together.

**Comment by matt-c1** [comment]
I posted steps to reproduce here, it's very simple to break:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2299240282
Another user proposed a partial solution, but not as a pull request because it's not a full fix:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2304870336
