### ISSUE TITLE
adjust distilled cfg wont take effect if

### ISSUE THREAD

**Issue by WingeD123** [lllyasviel/stable-diffusion-webui-forge#1200]
seems it's related to 'Persistent cond cache'
img1: first generate;
img2: generated after adjust distilled cfg with SAME prompt;
img3: generated after modify prompt(like add a comma);
img4: generated after modify prompt BACK(like delete the comma added);
all above fixed seed
img1 & img2 should be different, but got same.
img1 & img4 are different, so i believe distilled cfg is still working.
guess when only distilled cfg changes, 'Persistent cond cache' is used.

**Comment by IMTB682** [comment]
Same to me. Every time you adjust the distilled cfg, you have to reload the model for the new distilled cfg to take effect (you can trigger this by using the Swap method twice). However, this does take some extra time.

**Comment by ptits** [comment]
Still the same. Not work

**Comment by DenOfEquity** [comment]
As a temporary 'fix' you could disable **Persistent cond cache** in **Settings**->**Optimizations**, but this fully prevents cond caching so it's not ideal especially when using models with heavy text encoders.

For a better fix, I'll submit a PR. It's only a one line addition, so that a change to distilled CFG scale invalidates the cond cache. Though I'll add changes to step size for distilled CFG and CFG too, as I think 0.5 is too large a step with modern models.
https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1240

**Comment by kerizane** [comment]
Should be fixed now, please check and close this issue if it is.

**Comment by WingeD123** [comment]
works great
