### ISSUE TITLE
Sampler and CFG defaults are not being saved as defaults. 

### ISSUE THREAD

**Issue by andy8992** [lllyasviel/stable-diffusion-webui-forge#1323]
I use distilled models/lora so I am forced to change these each time. I have gone and updated the defaults dozens of times and it always defaults to 7 and DPM(++afiafdifpa) or whatever it's called. 

In the defaults section in settings, it says it's making the change and shows what the settings are but they are never respected. 

IMG2IMG tab is also the same.

**Comment by serick4126** [comment]
I’ve noticed that the default settings cannot be modified, and after investigating, I found that the configuration items named forge_preset are hard-coded in modules_forge/main_entry.py, making them difficult to change. 

While it would be possible to move these configuration items to a file like forge_preset.json, given the current situation where features are being frequently added, the existing setup might be more efficient.
(Additionally, the current form allows for the easy distribution of recommended settings by lllyasviel)

I’m interested to know if there are any plans to make the forge_preset more customisable in the future.

**Comment by andy8992** [comment]
Though you are able to save other settings that wouldn't be compatible with 7cfg and the given sampler. It doesn't allow me to set 4 steps as default.

Not to mention it DOES say it is changing the defaults when you go to save them. It just doesn't.

**Comment by Reavski-GH** [comment]
Having the same issue, made worse because my go-to models require specific settings/samplers. Having the UI claim to save the defaults, only for it change the settings to something incompatible when I wasn't looking must have shaved off at least a few years of my life before I realised what was happening.

Having a button/option to automatically override the baked-in settings with those from the edited user-config.json (they actually do get saved there) would be an excellent solution. As it is, starting the UI, reloading it or using the UI switcher ignores user-config wholesale.

**Comment by coghazard** [comment]
Same issue.

**Comment by MartyMcStarfox** [comment]
Very annoying :/

**Comment by serick4126** [comment]
PR[#1541](https://github.com/lllyasviel/stable-diffusion-webui-forge/pull/1541) has been merged so that the “All” preset now applies the settings saved in ui-config.json.
