### ISSUE TITLE
[FLUX.1] The Models (any quants) Just eat all my Resources after Latest Update.

### ISSUE THREAD

**Issue by Iory1998** [lllyasviel/stable-diffusion-webui-forge#1354]
Hi,
I am trying to use Flux. I have GGUF_Q4, Q6_K, Q8, the Fp16, and the nf4 v2, and I can barely get Forge working with Flux. It's a hit and miss. I have to constantly relaunch Forge, then hit generate and hope the models are correctly places in the VRAM. I am attaching a screenshot where Flux1-dev-bnb-nf4-v2 using all my 24GB or VRAM and 13GB of shared memory. That's not normal.
Out of 10 times, I can generate one image, and if I change the prompt, the models sometimes unload and then reload but then they use up more memory, or they just don't unload and stay in memory which gives me cuda-out-of-memory error.

I am running windows 11, and I have 32GB or RAM, and my RAM usage is always above 60%. 
FYI, I manage to run the fp16 in ComfyUI with controlnet and its take about 22GB or VRAM.
The difference is that models seem to load properly in VRAM and remain loaded.

![image](https://github.com/user-attachments/assets/8271bc1f-02c9-4b91-b041-87ba763afb1b)

**Comment by JenXIII** [comment]
I've checked out 95bc5865 while I wait for the new features to become stable

**Comment by Iory1998** [comment]
For anyone who is facing this problem, and if you have 24GB of VRAM, **just use Queue and CPU, remove any --pin-shared-memory --cuda-malloc --cuda-stream arguments.**  Shared turns on --pin-shared-memory. Refers to this post https://github.com/lllyasviel/stable-diffusion-webui-forge/discussions/395

That solved the problem for me for any model that is not the fp16. When I use the fp16, VRAM does not exceed 22GB but the app crashes after it finishes as it unloads the KModel, for some reason.

![image](https://github.com/user-attachments/assets/609eb9fe-792d-445b-b3ae-833e9d405810)

**Comment by lllyasviel** [comment]
![image](https://github.com/user-attachments/assets/89fee57e-9ead-4e73-8c66-1383196c4c31)
This means you will use 100% GPU memory to load weights with 0% memory to compute. So it is expected to be about 10x slower.

![image](https://github.com/user-attachments/assets/59e8af5a-5d2a-4efe-9f0f-3094c92c96e5)
This means you will use two workers move layers and compute together, but consider that you use 100% GPU memory with 0% memory to compute, this will not work because there is no free VRAM to compute.

![image](https://github.com/user-attachments/assets/77a1c16e-9a32-451c-b928-11cd3edb587f)
This mean you will use shared GPU memory, and it is doing that.

In this screenshot, everything works perfectly. It is slow because you set it to run in a slow mode to do specific tests.

**Comment by Iory1998** [comment]
I read your post earlier and I understood the meaning of that. Anyway, now any model that is no fp16 works fine. It would be good to remind people of what --pin-shared-memory --cuda-malloc --cuda-stream mean especially now that anyone using FLUX models will be tight on VRAM.

Thank @lllyasviel for your hard work and for your feedback.

**Comment by lllyasviel** [comment]
if your set GPU weights to lower, the two SWAP locations/methods will not cause any problem

**Comment by Iory1998** [comment]
Let me experiment and revert back to you.

**Comment by Iory1998** [comment]
@lllyasviel I set the GPU weights for 20000mb and it worked! Although when I changes the prompt it crashed but probably I kept the GPU set higher, but as you said, l could see the GPU memory slightly increases when the image was generating.
![image](https://github.com/user-attachments/assets/9ef195f0-cd86-4d7a-8600-850b90f56dae)
