### ISSUE TITLE
- Birefnet Background Removal - Spaces

### ISSUE THREAD

**Issue by danilomaiaweb** [lllyasviel/stable-diffusion-webui-forge#1364]
The birefnet for background removal (Spaces) continues to save the original image instead of the processed image without the background.

**Comment by DenOfEquity** [comment]
It works for me with right-click->Save image; the save icon in top-right does save incorrectly.

**Comment by DenOfEquity** [comment]
I looked into this a bit more:
The save/download icon saves the second of the two slider images, this is a 'choice' (more like arbitrary selection) made in the slider code. But the masked image output of background removal must be the first image, otherwise you can't see the result - the original image would be underneath the transparent parts of the output image. Also, the save icon can't be hidden due to a bug in the slider code.
So this isn't something that can reasonably be fixed/changed on the Forge side.

**tl,dr**: use _context menu > Save image_
