### ISSUE TITLE
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

### ISSUE THREAD

**Issue by wujun200999** [lllyasviel/stable-diffusion-webui-forge#1479]
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

**Comment by wujun200999** [comment]
https://github.com/chenfei-wu/TaskMatrix/issues/250#issuecomment-1498285842

ty!

**Comment by DiamondsForTears** [comment]
Commenting here for other noobs such as myself running into this issue.
I found out that they meant to actually open up webui-user.bat in a code reading program like visual studio and manually add in "set no_proxy=localhost, 127.0.0.1, ::1" into the python.

Why is that not there to begin with? Asking because I am not experienced enough with any of this to know why.

**Comment by wxj630** [comment]
[may try downgrade pydantic==2.10.6](https://github.com/gradio-app/gradio/issues/10649#issuecomment-2675018488)
