### ISSUE TITLE
[Feature Request]: Make it easier to reference existing A1111 checkout

### ISSUE THREAD

**Issue by huchenlei** [lllyasviel/stable-diffusion-webui-forge#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Context: #147

Currently we have commented out code in webui-user.bat, that sets venv path and several model paths. However, this does not cover everything and is error prone when there are changes needed.

### Proposed workflow

Add a single commandline arg to reference A1111 checkout. This commandline arg should also track ControlNet models directory, and ControlNet preprocessor model directory.

**Comment by strawberrymelonpanda** [comment]
I'd welcome this, I think it's what Comfy does.

In the meantime, I've just symlinked all of my model folders over.

**Comment by ArnorWing** [comment]
I am using 'old' A1111 syntax and it works. 
set COMMANDLINE_ARGS=--ckpt-dir h:\\Stable-Diffusion\\stable-diffusion-webui\\models\\Stable-diffusion\\ --vae-dir h:\\Stable-Diffusion\\stable-diffusion-webui\\models\\VAE\\ --lora-dir h:\\Stable-Diffusion\\stable-diffusion-webui\\models\\Lora\\ --embeddings-dir h:\\Stable-Diffusion\\stable-diffusion-webui\\embeddings\\ --esrgan-models-path h:\\Stable-Diffusion\\stable-diffusion-webui\\models\\ESRGAN\\

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/blob/forge/master/docs/how-to-use.md#preparation

If you can do git, this is the easiest way to switch between OG A1111 and Forge

**Comment by Gothmoth88** [comment]
the easiest wy woudl be to put a path option into teh settings not? i mean a lot of non coders are intertesd isn AI. you make a ONE CLOCK windows installation so you must have these people in mind. but bothering with comandline parameters is not what these users will like to do. otherwise they would not download a one click solution. i don´t want to learn python or become an AI coder, i have enough to worry about in my real job..... i just want to create images. ;)

**Comment by Gothmoth88** [comment]
> I am using 'old' A1111 syntax and it works. set COMMANDLINE_ARGS=--ckpt-dir h:\Stable-Diffusion\stable-diffusion-webui\models\Stable-diffusion\ --vae-dir h:\Stable-Diffusion\stable-diffusion-webui\models\VAE\ --lora-dir h:\Stable-Diffusion\stable-diffusion-webui\models\Lora\ --embeddings-dir h:\Stable-Diffusion\stable-diffusion-webui\embeddings\ --esrgan-models-path h:\Stable-Diffusion\stable-diffusion-webui\models\ESRGAN\
> 
> CONTROLNET folders can be shared in CN settings
...................

does not work for me i only get an error message. 
but i guess it´s because i am using stability matrix + A1111 and the symlinks mess with it.

Traceback (most recent call last):
  File "I:\Stable Diffusion Forge\webui\launch.py", line 1, in <module>
    from modules import launch_utils
  File "I:\Stable Diffusion Forge\webui\modules\launch_utils.py", line 14, in <module>
    from modules import cmd_args, errors
  File "I:\Stable Diffusion Forge\webui\modules\cmd_args.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir, sd_default_config, sd_model_file  # noqa: F401
  File "I:\Stable Diffusion Forge\webui\modules\paths_internal.py", line 9, in <module>
    sys.argv += shlex.split(commandline_args)
  File "shlex.py", line 315, in split
  File "shlex.py", line 300, in __next__
  File "shlex.py", line 109, in get_token
  File "shlex.py", line 210, in read_token
ValueError: No escaped character
