### ISSUE TITLE
Flux LORA Categorization

### ISSUE THREAD

**Issue by lunar-studio** [lllyasviel/stable-diffusion-webui-forge#1703]
Hi. Just wondering if anyone has a way to separate LORAs into the Flux Lora Tab.
I’ve downloaded a bunch meant for Flux but they only appear in the All tab with hundreds of others that I should probably get rid of… Please let me know.

**Comment by SvenErik1968** [comment]
Here is how I organize all my LoRA's. 

First change this under `Settings > Extra Networks` and un-check `Always show all networks on the Lora page (otherwise, those detected as for incompatible version of Stable Diffusion will be hidden` on the Lora page that you find towards the end of that page. Reload the UI. This will hide the LoRA's that are not compatible with the checkpoint you are not using (you will have to do a refresh on the Lora-tab when you change the base type of LoRA).

Secondly, organize your LoRA's in sub-folder.

First by base checkpoints that you use:
```
SD 1.5
SDXL 1.0
...
Flux.1 D
Flux.1 S
```

Then create folders for categories under each. I use something like this:

```
\Background
\Base Model
\Character
\Clothing
\Clothing\Dresses & Skirts
\Clothing\Fetish
\Clothing\Lingerie
\Clothing\Tops
\Concept
\Concept\BodyMods
\Concept\Objects
\Detail
\Expressions
\Motion
\Poses
\Style
\Style\Artists
\Style\Camera
\Style\Era
\Style\Lighting
\Style\Medium
\Tools
```

If you look at the CivitAI page for the individual LoRA's, you will find one or more categories for it, use the one who makes the most sense for you, or come up with your own.

**Comment by skibidiskoobidi** [comment]
As SvenErik suggested, I do the same. Forge drills down the directories and generates buttons per folder name.

**Comment by lunar-studio** [comment]
That’s awesome and thank you for the tips. I only recently started using Stability Matrix to manage the various SD versions and to more easily share libraries and LORAs. One of the downsides is that I tried putting the Flux models in a Flux folder and they weren’t showing up in the Matrix browser so I had stopped doing that. But perhaps I just need to ignore Matrix and just work this way instead.

**Comment by SvenErik1968** [comment]
You can also use similar folder ordering with the checkpoints under the `Stable-diffusion` folder.
```
Pony
SD 1.5
SD 3
SDXL 1.0
SDXL Hyper
SDXL Lightning
SDXL Turbo
Flux.1 D
Flux.1 S
```
And if wanted, sub-folders under them again:
```
...
Pony
Pony\Anime
Pony\Realistic
...
```

**Comment by bkosowski** [comment]
@lunar-studio Did any suggestions work for you? Please close the issue, if so.
