### ISSUE TITLE
GPPGAN not working, model not downloading

### ISSUE THREAD

**Issue by rubenmejiac** [lllyasviel/stable-diffusion-webui-forge#1717]
Trying to use GFPGAN for restoration in Extras tab, does not download model and gives error:

![image](https://github.com/user-attachments/assets/425d8a45-c61b-4bce-8f6f-ba5d865228dc)

Codeformer method of restoration works fine, it downloads the model and seems to function properly.

Contents of relevant model folders:

```
models/Codeformer --> codeformer-v0.1.0.pth
models/ESRGAN --> ESRGAN_4x.pth
models/GFPFAN --> detection_Resnet50_Final.pth, parsing_parsenet.pth
models/RealESRGAN --> RealESRGAN_x4plus.pth
```
Sysinfo:

[sysinfo-2024-09-06-05-30.json](https://github.com/user-attachments/files/16903312/sysinfo-2024-09-06-05-30.json)

**Comment by Tekamania** [comment]
For your info when i installed for the first time SD Forge 2 months ago or so and i checked the GFPGAN checkbox to download the only 2 things that it downloaded where: detection_Resnet50_Final.pth, parsing_parsenet.pth and then i set manually GFPGANv1.4.pth inside the folder BUT i dont know what of these 2 models are using right now SD Forge because in the cmd log it says its being using GFPGAN but i dont know if its "real" or its using resnet parsenet. The first time i needed to stop and re-launch and it downloaded detection_Resnet50_Final.pth, parsing_parsenet.pth but not GFPGAN 1.4 or other versions. Right now GFPGAN is broken for ComfyUI and i dont know if its affecting to SD Forge too and thats because SD Forge dont download it.

Could be nice if any colaborator could say if SD Forge really uses GFPGAN 1.4 and not resnet parsent installing it manually inside the folder as i did :)

**Comment by rubenmejiac** [comment]
Also installed the GFPGANv1.4.pth model manually, and I share your doubts about if Forge is actually using it internally.

**Comment by DenOfEquity** [comment]
The code that handles model downloading will only download the model if no `.pth` model files exist in the GFPGAN directory. But if you used codeformer at any point, it already downloaded the supplementary models `detection_Resnet50_Final.pth` and `parsing_parsenet.pth` and stored them in the GFPGAN directory.
I've added some code to handle this case, but it doesn't matter how the model gets to the GFPGAN directory, manually or automatic download, only that it is there.
Also found a bug relating to using visibility < 1, with both codeformer and GFPGAN.
Code flow is correct to be using GFPGAN, once the model is in place. And results seem reasonable to me.

**Comment by rubenmejiac** [comment]
Thank you for the changes, I just updated and everything is working.
