### ISSUE TITLE
Why is the flux realism sampler code hidden in a zipped blockly import?

### ISSUE THREAD

**Issue by RandomGitUser321** [lllyasviel/stable-diffusion-webui-forge#1733]
I was having a hell of a time trying to figure out what the new "flux realism" sampler was (I'm guessing it's similar to comfyui's dpmpp_2s_ancestral that was semi-recently adapted to work with flux and that also takes 2x as long per step), but then I realized it was hidden in the zipped up blockly code.

With all the scammy stuff that's been going around github lately, stuff like this makes people think of one of two things:

A) People hiding malware/exploits within the zipped code
B) People "borrowing" other people's code and making it harder for the average person to easily spot and point out

Not directly accusing you of either of these, just saying that moves like this likely look suspicious to a lot of people. I know it's easy to unzip it and inspect the code to see, but why do it like this? Do you need help porting it to join the other samplers in the regular codebase?

**Comment by zdaar** [comment]
It looks like malware. Even dezipped it is highly obfuscated. Not a good look

**Comment by FurkanGozukara** [comment]
> It looks like malware. Even dezipped it is highly obfuscated. Not a good look

What the hack?

**Comment by BNP1111** [comment]
Dude, when an old friend presents you with his new toy to play with, can't we allow a testing period first? If you're particularly worried about your millions of dollars going missing, you can choose not to use it or just walk away, can't we allow for a little more trust?

**Comment by zdaar** [comment]
This is the unzip
https://gist.github.com/zdaar/9fd0af678eb8d55fe8e4a1fa14894fdd

I am not saying it is malware, just saying it looks shady. Dynamic imports, everything is super obfuscated, is this the google's blocky lib spitting out this ? Sure is developer unfriendly

**Comment by lllyasviel** [comment]
Hi,

The flux realistic sampler is a new family of “semi”-ancestral samplers, ie, only a certain range of steps are ancestral. This is based on some observations that partial ancestral ODEs can benefit Flux’s partial range of steps, like details, while avoiding uncertainty and distortion on higher range, like global structure. 

and also worked hard on some math stuff to figure out the correct and optimal ancestral formulation for special flow models (eg, Flux) with special time step shift like `math.exp(mu) / (math.exp(mu) + (1 / t - 1) ** sigma)`. The current k-diffusion’s ancestral formulation does not work well for these.

This sampler currently has two versions: a normal one and a slow one (the slow one uses 2nd order double denoising so it is about 2x slow). Also it seems the slow one is a bit unstable and I am going to check when I have free time next week

Forge official codes are regulated by GitHub ToS and EULA, and we endorse the integrity of files. Please do not replace files from untrusted providers to avoid malicious concerns. Also the current `exec` in codes only receive completely static file, ie, it does not receive user/dynamic inputs, and the current usage is in line with [pep-0338](https://peps.python.org/pep-0338/)

Google Blockly is a messy prototyping tool. Codes will be rewritten when necessary. Since there is also a plan to rewrite some important samplers into [torch cpp extensions](https://pytorch.org/tutorials/advanced/cpp_extension.html) to completely avoid cuda clock problems, the rewritten code may in either python or cpp. Also the prototype GoogleBlockly runtime supports more than just python. I also have a Matlab runtime that can use methods like

https://hub.hku.hk/bitstream/10722/215521/1/Content.pdf

https://github.com/sai-bi/L1Flattening

https://www.cse.cuhk.edu.hk/~leojia/projects/texturesep/

to achieve certain applications, and can be called from python seamlessly (by calling dll/so libs). And these methods are nearly impossible to implement in plain python since scipy’s sparse optimization is not as efficient as Matlab as far as I know. Those things are important in some illumination manipulation and [intrinsic imaging](https://people.tuebingen.mpg.de/mkiefel/projects/intrinsic/) stuffs.

**Comment by FurkanGozukara** [comment]
@lllyasviel thank so much for explanation

i just tested ipndm on SwarmUI for FLUX and it seems like improving quality and realism of images

Have you tested it, seen it?

**Comment by lllyasviel** [comment]
Forge's ipndm is not maintained by me

**Comment by yoinked-h** [comment]
@lllyasviel 
hi, would like to get some more clarity on the code/blockly, as it seems obfuscated without the right tools to open. would be neat to see this code in python / be able to be edited clearly by the end user; if not then can you provide tools to de-obfuscate the code? thanks

**Comment by Pavel61981** [comment]
this is what whining leads to ahah
