### ISSUE TITLE
NaN shows up when adjusting token/LoRA strength with Ctrl+Arrow keys

### ISSUE THREAD

**Issue by arzam16** [lllyasviel/stable-diffusion-webui-forge#1815]
Commit: 8bd7e0568f4d942f4d17bcc7a6966e92d2b897eb
Tested on: Firefox 130 running in Safe mode (no extensions, no themes, all defaults), the OS is the latest Linux Mint
Steps to reproduce:
1. Launch webui, wait for it to load
2. Type anything into the prompt box
3. Select any token, doesn't matter how selection is done - could be with double mouse click, Shift+Ctrl+Arrows etc.
4. Press Ctrl+Arrow Up or Ctrl+Arrow Down, witness `token` turning into `(token:NaN)` :clown_face: 
Does anything related to this issue pops up in the Browser Console: no

**Comment by ryankhart** [comment]
Same, and if there isn't already a strength set for a term, ctrl+up and ctrl+down just does what it does in any other text box in the browser on any web page.

**Comment by ryankhart** [comment]
I found the culprit for me. I had recently installed sd-civitai-browser-plus, which is normally a must have extension for all A1111 flavors of installs for me, but on Forge, it broke the ctrl+up and ctrl+down arrow functionality, as well as preventing the full page image viewer when clicking on a generated image, as soon as I disabled this extension, reloaded my UI and refreshed the page, it fixed the problem for me.

I'm not saying that this issue should or shouldn't be closed due to this issue being with an extension. Maybe one of the contributors or maintainers can weigh in on that on who's most equipped to resolve this issue. But at the very least, I think there should be an open issue on the sd-civitai-browser-plus repo.
