### ISSUE TITLE
Forge not working with Flux...c10.dll error?

### ISSUE THREAD

**Issue by hooner** [lllyasviel/stable-diffusion-webui-forge#1951]
Hi there,

Running any Flux model in Forge results in a timeout. I get the following from Windows EventViewer. I have tried repairing Python, and installing Foreger both the "one-click" way, and the more advanced way described here.

Faulting application name: python.exe, version: 3.10.6150.1013, time stamp: 0x62e84c21

Faulting module name: c10.dll, version: [0.0.0.0](http://0.0.0.0/), time stamp: 0x6655ec14

Exception code: 0xc0000005

Fault offset: 0x0000000000063064

Faulting process id: 0x0xF24

Faulting application start time: 0x0x1DB1332476CB8ED

Faulting application path: C:\Users\xxx\AppData\Local\Programs\Python\Python310\python.exe

Faulting module path: Z:\forge\stable-diffusion-webui-forge\venv\lib\site-packages\torch\lib\c10.dll

Report Id: 7366f343-de3a-4c9a-b62f-06695b116dd6

Faulting package full name:

Faulting package-relative application ID:

**Comment by akapendragon** [comment]
If you have a 14th-gen or 13th-gen Intel CPUs, it may be due to the over voltage issue they found this summer.  I have an alienware 16 with top specs (+ my own) and started having the python issues a few weeks ago.  None of them happen on a 2 yr old alienware.  Two days days ago i read there was a bios update to fix the problem, which included intel fixes. Today I was able to do over 300 images in a row when for the past month i couldn't do over 3 without the python error (even getting the damn thing to run would fail 4 time out of 5). After the bios update, no issues so far.

Intel Core 13th and 14th Gen Desktop Instability Root Cause Update -> https://community.intel.com/t5/Blogs/Tech-Innovation/Client/Intel-Core-13th-and-14th-Gen-Desktop-Instability-Root-Cause/post/1633446#M40

**Comment by hooner** [comment]
Hi there, this really helped thanks, as I have a  i7-14700K. I can run some Civitai hosted models now.  Most still fail, but with memory related errors instead :) or they run and stall at 95%.
