### ISSUE TITLE
"Override Settings" Gradio Dropdown not Working

### ISSUE THREAD

**Issue by altoiddealer** [lllyasviel/stable-diffusion-webui-forge#2096]
In A1111 / ReForge - when sending params from PNG Info, some multi-select Options will appear in a gradio accordion "Override Settings".

The code related to this is identical in both Forge -- and A1111 / ReForge.

However, Forge is now using Gradio 4 so the code is no longer working and requires updating.

I've poked around at it but I really suck at Gradio.

![sendtotxt2img](https://github.com/user-attachments/assets/0ff31cd2-3bf1-48c4-b7aa-652906f513a9)

## Expected Result:

![override settings](https://github.com/user-attachments/assets/0032816c-0a77-498d-a32b-ccb1210d8f96)

---

## Findings

From [infotext module get_override_settings](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/modules/infotext_utils.py#L468)

![Paste Comparison](https://github.com/user-attachments/assets/4fd5b393-e53b-40e2-8986-d8315a2633ae)

---

From [ui module create_override_settings_module](https://github.com/lllyasviel/stable-diffusion-webui-forge/blob/main/modules/ui.py#L259)

PyLance shows that the `change()` and `update()` methods behave differently in Gradio 4.  I've tried messing around here but could not make this work.

![Screenshot 2024-10-16 123501](https://github.com/user-attachments/assets/90803a9e-407e-41be-94f4-a7c067a24820)

![Screenshot 2024-10-16 123550](https://github.com/user-attachments/assets/3626e037-5dfa-4df9-b768-68d46a4d66cf)

**Comment by DenOfEquity** [comment]
I think the override dropdown itself is working correctly. I've had it show up with 'face_restoration' and 'sigma_min'/'sigma_max' overrides.
The issue here is that 'Clip skip' isn't recognised as overridable - due to the update making it Forge managed it lost the tag that enabled the infotext system to translate it to the internal name 'CLIP_stop_at_last_layers'.

If you have time, take a look at #2099
