### ISSUE TITLE
Hiresfix checkpoint only works on same architecture

### ISSUE THREAD

**Issue by jordanjay29** [lllyasviel/stable-diffusion-webui-forge#2107]
The recent hiresfix #2100 will only work across same architecture models (e.g. SD1.5 to 1.5, XL/Pony to XL/Pony, Flux to Flux) due to the change in requirements for VAE and possibly text encoders. 

Could we have an additional field to select the TE/VAE like on top?

**Comment by altoiddealer** [comment]
`hr_forge_additional_modules` sounds like a good idea

**Comment by DenOfEquity** [comment]
You won't get good results with latent upscale between architectures, because the latents are not compatible. You *can* hiresfix any->any with a suitable upscale method, like Lanczos. I've tested 1.5 <-> XL (both ways) and 1.5 -> Flux.
There is an issue if there is incompatibility between selected VAE/TE and the two models - i.e. trying to use a Flux model that doesn't include text encoders for the highres pass; because the necessary additional models are not included (unless also included in the first pass). Even 1.5 -> 1.5 can fail here, if the second pass model doesn't include a VAE.

I'm looking at adding highres additional modules. Currently working, but still some issues around infotext loading.

**Comment by jordanjay29** [comment]
I expected that the output would be trickier to get right, but even having the ability to do so in Forge could at least make for some good experiments. Sometimes even bad output is good output, if you know what I mean. 

A hires additional modules field would resolve it well!

**Comment by andy8992** [comment]
Possible suggestion related to this, it may be nice if it could render the batch as one then hiresfix them as another. So render all 5 as SD 1.5 and then do them all as a hires batch with xl, to cut down on back and forth model loading for those of us with less resources.

**Comment by jordanjay29** [comment]
Last comment, seems like Forge will only perform the checkpoint switch one way for a batch. So using batch count over 1 means subsequent images in the batch will be run by the checkpoint and additional modules added for the hiresfix. This is more of a QOL issue than a showstopper, as batches of 1 can be run and seeds manually incremented, but I doubt it's an intentional feature.

**Comment by DenOfEquity** [comment]
It's trying to use the old way of reloading the model, which does nothing. Looks like it should be a one line fix to `modules/processing.py` line 931, to use the new function `sd_models.forge_model_reload()`. Testing now.

**Comment by jordanjay29** [comment]
0c97a5347a424741f40c66aabec6ee595aeb5895 seems to have resolved the last issue. Thanks again, closing as I have no more complaints on this subject.
