### ISSUE TITLE
UI won't load after update

### ISSUE THREAD

**Issue by Bigbigliar** [lllyasviel/stable-diffusion-webui-forge#905]
![image](https://github.com/user-attachments/assets/2341e823-a6af-405f-a0fc-c7ecb5445c8b)
![image](https://github.com/user-attachments/assets/b284fd24-956f-4920-87fe-9f2eb3b67347)

**Comment by Corn0nTheRob** [comment]
I ran into this problem as well. I found that reinstalling the application and copy/pasting models folder from the old application works. I would personally avoid updating right now, as there are several issues that are impacting ui performance

**Comment by R4llik** [comment]
Try reinstalling and dont use any extensions if possible cuz for me that was problem

**Comment by R4llik** [comment]
Update: After testing some extensions i found out that problem for me was "canvas zoom" extension because it tries to modify old gradio while on automatic 1111 forge gradio was recently updated so it causes webui to freeze. If you currently have canvas zoom installed then you will have to remove it from /extensions folder and reinstall automatic1111forge. Hope it helps :D

**Comment by Koxae** [comment]
Many other extensions cause an error when loading after the update. It is better not to install the update for now.

**Comment by Bigbigliar** [comment]
I rolled back to an older version and everything worked again, I didn't want to install everything from scratch, many applications and settings would be lost, downgrade is the best solution for now
