### ISSUE TITLE
Stop infinite generation failure

### ISSUE THREAD

**Issue by xam0482** [lllyasviel/stable-diffusion-webui-forge#929]
不能停止 除非刷新页面

**Comment by itasky** [comment]
same issue. I can't stop GENERATE FOREVER, i click on CANCEL option but no effect.

**Comment by matt-c1** [comment]
I posted steps to reproduce here, it's very simple to break:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2299240282
Another user proposed a partial solution, but not as a pull request because it's not a full fix:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/1292#issuecomment-2304870336
